@echo off
color 0d
del /q /s /f "%TEMP%\*.*"
del /q /s /f "%SystemRoot%\Temp\*.*"
del /q /s /f "%SystemRoot%\Prefetch\*.*"
del /q /s /f "%SystemRoot%\System32\winevt\Logs\*.*"
del /q /s /f "%SystemDrive%\inetpub\logs\LogFiles\*.*"
del /q /s /f "%SystemRoot%\WindowsUpdate.log"
del /q /s /f "%LocalAppData%\Microsoft\Windows\Explorer\thumbcache_*.db"
del /q /s /f "%LocalAppData%\Microsoft\Windows\FontCache\*.*"
del /q /s /f "%LocalAppData%\Microsoft\Windows\WER\ReportQueue\*.*"
del /q /s /f "%AppData%\Microsoft\Windows\Recent\*.*"
del /q /s /f "%LocalAppData%\Temp\*.*"
del /q /s /f "%LocalAppData%\Google\Chrome\User Data\Default\*Cache*.*"
del /q /s /f "%AppData%\Mozilla\Firefox\Profiles\*\cache2\*.*"
del /q /s /f "%LocalAppData%\Microsoft\Edge\User Data\*\Cache\*.*"
del /q /s /f "%AppData%\Microsoft\Outlook\*.log"
del /q /s /f "%AppData%\Microsoft\Teams\logs\*.log"
del /q /s /f "%AppData%\Slack\logs\*.log"
del /q /s /f "%LocalAppData%\Microsoft\Teams\Service Worker\CacheStorage\*.*"
exit
